### ISSUE TITLE
isPhenotype bug(s?)

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/NHANES-metadata#31]
Hi Rafael and Jason,
  In setting up the non-phenotype work, I had pointed you to the vignette VariableClassification.Rmd in the phonto package.
But somehow the examples given there don't all seem to have been copied over - 
I draw your attention to this code:
##comments - most variables end with an LC but not all...so we also
 ## look at the description - the SasLabel doesn't work as they abbreviate
 ##comments in weird ways
 g1 = grep("LC$", xx$Variable)
 g2 = grep("*[Cc]omment [Cc]ode$", xx$Description)
 outPut[union(g1,g2)] = "Comment"
 

  so any variable whose name ends in LC is a comment, and not a phenotype....but looking at the isPhenotype column in the Metadata, these are all labeled as phenotypes.
  I did not exhaustively check the other examples of non-phenotypes, but it would be good to ensure that these are synced up.

  Not sure if this is you, or Sam, but in this table
Metadata.QuestionnaireVariables
  the column named UseConstraints should be named Target...

**Comment by rsgoncalves** [comment]
We added all (missing) regular expressions applicable to SasLabels to our `blocklist_regexps.txt`. Then, for the expressions in [VariableClassification.md](https://github.com/ccb-hms/phonto/blob/main/docs/vignettes/VariableClassification.md) that are applicable to variable identifiers (rather than labels), we added to our [`blocklist_table.csv`](https://github.com/ccb-hms/NHANES-metadata/blob/master/code/resources/blocklist_table.csv) all the variable-table pairs that match such regular expressions. The tags in the R code are preserved in a `Tag` column in that table, and then in a `Comment` column we have the reason for inclusion of that variable in the table—here we include the regular expressions that were used to derive the entries. 

As I mentioned, there some exceptions to one of the regular expressions — variables that end in "LC" but that are not comments. For example [LB2ALC](https://wwwn.cdc.gov/Nchs/Nhanes/2001-2002/VIT_2_B.htm#LB2ALC), [VIXPLC](https://wwwn.cdc.gov/Nchs/Nhanes/2001-2002/VIX_B.htm#VIXPLC)). Such variables that are phenotypes but match one of of our non-phenotype patterns are listed in the newly created [`allowlist.csv`](https://github.com/ccb-hms/NHANES-metadata/blob/master/code/resources/allowlist.csv). 

The next release will include these updates.

Regarding the column names of Metadata.QuestionnaireVariables, it is an import error during the DB build.

**Comment by rsgoncalves** [comment]
closed via a8ba61a and will be in release v3.10.0.
